name = "QuantumModpack"
author = "Quantum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "05d8bfab8bd65e7f55893bc786eb05be811bf02e1666235b5a7e36d73e8a68d3"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
