name = "QuantumModpack"
author = "Quantum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4fe4f47ae307455187818ea848f48a5a230a48c4e3d9280b0e8e9cd96c7c7c86"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
