name = "QuantumModpack"
author = "Quantum"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3adbbd6ccfb8733a49edc77923dfac8bcb4dae6b95339e8006d664f7461e40c"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
